// Electric Strike Cross Reference Chart — CAMDEN 2026 US Price List R6.pdf, p.15
const CAMDEN_XREF_META = {
  source_pdf: "CAMDEN 2026 US Price List R6.pdf",
  page: 15,
  generated: "2026-09-10",
};

const CAMDEN_XREF = [
  {
    description: "3/4\" Surface Mount RIM Strike",
    camden: ["CX-EPD1289L"],
    rci: "F0162",
    hes: "9500/9600",
    adamsRite: "N/A",
    trine: "4800F",
    vonDuprin: "6300",
    locknetics: "RS-300-F-32D",
    notes: "Camden Includes Preload, Security and 3 Hour Fire Rating",
  },
  {
    description: "1/2\" Surface Mount RIM Strike with 2 Spacer Plates",
    camden: ["CX-EPD1299L"],
    rci: "0163",
    hes: "9400",
    adamsRite: "74R2",
    trine: "4590",
    vonDuprin: "N/A",
    locknetics: "RS-2000",
    notes: "Camden Includes Preload Security and 2 Spacer Plates",
  },
  {
    description: "Low Profile 'All in One' Fire Rated Electric Strike",
    camden: ["CX-ED1689L-4"],
    rci: "N/A",
    hes: "1500",
    adamsRite: "N/A",
    trine: "4100",
    vonDuprin: "N/A",
    locknetics: "N/A",
    notes: "Camden Includes 4 Faceplates, 3 Hour Fire Rating, and Monitoring as Standard",
  },
  {
    description: "Dual Monitor 'All in One' Fire Rated Electric Strike",
    camden: ["CX-ED1799L-8"],
    rci: "N/A",
    hes: "1600",
    adamsRite: "N/A",
    trine: "N/A",
    vonDuprin: "6216",
    locknetics: "N/A",
    notes: "Camden Includes 8 Faceplates, 3 Hour Fire Rating, and Monitoring as Standard",
  },
  {
    description: "'All in One' Grade 1 Fire Rated Electric Strike",
    camden: ["CX-ED1579L"],
    rci: "F2164",
    hes: "1006CLB",
    adamsRite: "N/A",
    trine: "4100CDBM",
    vonDuprin: "6400",
    locknetics: "MS100F",
    notes: "Camden Includes 5 Faceplates, 3 Hour Fire Rating, and Latch Monitoring as Standard",
  },
  {
    description: "Cylindrical, Grade 1, Low Profile",
    camden: ["CX-ED1079"],
    rci: "L65U",
    hes: "5000C",
    adamsRite: "N/A",
    trine: "N/A",
    vonDuprin: "4200",
    locknetics: "CS-450",
    notes: "Camden Includes 3 Faceplates as Standard",
  },
  {
    description: "Cylindrical Grade 1, Standard Depth",
    camden: ["CX-ED1079D"],
    rci: "S65U",
    hes: "5200C",
    adamsRite: "N/A",
    trine: "4200",
    vonDuprin: "N/A",
    locknetics: "CS-750",
    notes: "Camden Includes 3 Faceplates as Standard",
  },
  {
    description: "Cylindrical, Grade 1, Fire Rated Electric Strike",
    camden: ["CX-ED1410"],
    rci: "F4114",
    hes: "4500",
    adamsRite: "7240",
    trine: "N/A",
    vonDuprin: "6200",
    locknetics: "N/A",
    notes: "Camden Includes 1 Faceplate (ANSI w/ Square Corners) as Standard, and 90 min. Fire Rating",
  },
  {
    description: "Cylindrical, Grade 1, Fire Rated Electric Strike, Low Profile",
    camden: ["CX-ED1420"],
    rci: "N/A",
    hes: "5300",
    adamsRite: "N/A",
    trine: "N/A",
    vonDuprin: "N/A",
    locknetics: "N/A",
    notes: "Camden Includes 1 Faceplate, 90 min. Fire Rating",
  },
  {
    description: "Cylindrical, Grade 2, Low Profile",
    camden: ["CX-ED2079"],
    rci: "L65U",
    hes: "N/A",
    adamsRite: "N/A",
    trine: "4200",
    vonDuprin: "5100",
    locknetics: "CS-450",
    notes: "Camden Includes 3 Faceplates",
  },
  {
    description: "'Universal' Grade 1, Narrow Stile Aluminum",
    camden: ["CX-ED1309"],
    rci: "N/A",
    hes: "N/A",
    adamsRite: "7100",
    trine: "N/A",
    vonDuprin: "N/A",
    locknetics: "N/A",
    notes: "Camden Includes 2 ANSI Faceplates (CX-ED1309 Series)",
  },
  {
    description: "Outdoor Rated, Grade 1 Electric Gate Strike",
    camden: ["CX-ED1959-MB", "CX-ED1959RM-MB"],
    rci: "N/A",
    hes: "N/A",
    adamsRite: "N/A",
    trine: "EN400",
    vonDuprin: "N/A",
    locknetics: "N/A",
    notes: "Camden Includes a Metal Surface Mounting Box",
  },
];

// Magnetic Lock Cross Reference — a12123_Magnetic_Lock_Cross_Reference.pdf (MKTG-LIT-CROSSRF-MAGLOCKS)
// Separate document from the R6 price list — it has no equivalent magnetic-lock chart.
const CAMDEN_MAGLOCK_XREF_META = {
  source_pdf: "a12123_Magnetic_Lock_Cross_Reference.pdf (MKTG-LIT-CROSSRF-MAGLOCKS)",
  generated: "2026-09-10",
};

const CAMDEN_MAGLOCK_XREF = [
  {
    description: "300 lbs Surface Mount",
    camden: ["CX-90S-03"],
    rci: "8375",
    securitron: "VM300",
    schlage: "N/A",
    sdc: "1583, E300",
    dynalock: "N/A",
    rofu: "8003S",
    alarmControls: "300S",
  },
  {
    description: "300 lbs. Mortise Mount",
    camden: ["CX-90M-03"],
    rci: "8365",
    securitron: "N/A",
    schlage: "N/A",
    sdc: "N/A",
    dynalock: "N/A",
    rofu: "8003M",
    alarmControls: "N/A",
  },
  {
    description: "600 lbs. Surface Mount",
    camden: ["CX-91S-06"],
    rci: "8371",
    securitron: "M38",
    schlage: "40 SERIES",
    sdc: "1581",
    dynalock: "2511",
    rofu: "8005",
    alarmControls: "600S",
  },
  {
    description: "600 lbs. Surface Mount w/adj. Timer/Lock Sensor & LED",
    camden: ["CX-91S-06TDS"],
    rci: "8371-DSS/SCS",
    securitron: "M38DLS",
    schlage: "M420P+MBS+DPS+RTD",
    sdc: "1581-TDBL, E600",
    dynalock: "2511-DYNLED",
    rofu: "8005X001",
    alarmControls: "600LB",
  },
  {
    description: "600 lbs. Mortise Mount",
    camden: ["CX-91M-06"],
    rci: "8360",
    securitron: "M34R",
    schlage: "320M",
    sdc: "1591",
    dynalock: "2600",
    rofu: "8000",
    alarmControls: "N/A",
  },
  {
    description: "1200 lbs. Surface Mount",
    camden: ["CX-91S-12"],
    rci: "8310",
    securitron: "M68",
    schlage: "70 SERIES",
    sdc: "1571",
    dynalock: "2011",
    rofu: "8011LC",
    alarmControls: "1200S",
  },
  {
    description: "1200 lbs. Surface Mount w/adj. Timer/Lock Sensor & LED",
    camden: ["CX-91S-12TDS"],
    rci: "8310-DSS/SCS",
    securitron: "M68DLS",
    schlage: "N/A",
    sdc: "1571-TDBL, E1200",
    dynalock: "2011-VOPLED",
    rofu: "8011-002",
    alarmControls: "1200LB",
  },
  {
    description: "1200 lbs Surface Mount Double Mag Lock",
    camden: ["CX-92S-12"],
    rci: "8320",
    securitron: "DM62",
    schlage: "72 SERIES",
    sdc: "1572",
    dynalock: "2022",
    rofu: "N/A",
    alarmControls: "1200D",
  },
  {
    description: "1200 lbs. Surface Mount Double Mag Lock w/adj. Timer/Lock Sensor & LED",
    camden: ["CX-92S-12TDS"],
    rci: "8320-2DSS/SCS",
    securitron: "DM62BD",
    schlage: "N/A",
    sdc: "1572-TDBC",
    dynalock: "2022VOP2LED2",
    rofu: "8022-002",
    alarmControls: "1200DLB",
  },
  {
    description: "1200 lbs. Gate Lock w/Lock Sensor",
    camden: ["CX-94S-12LS"],
    rci: "8380",
    securitron: "M62FG",
    schlage: "M490G",
    sdc: "1575",
    dynalock: "2013-DYN",
    rofu: "8040-002",
    alarmControls: "1200WD",
  },
];

// Column Switch Comparison — 2026-09-11-camden-bea-wikk-crossref.pdf
// Prepared by The ASH Team (not an official Camden/BEA/Wikk document). A feature/spec comparison
// broken out by product variant, not a part-number cross reference — no search box needed.
const CAMDEN_COLSWITCH_META = {
  source_pdf: "2026-09-11-camden-bea-wikk-crossref.pdf",
  prepared_by: "The ASH Team",
  generated: "2026-09-11",
};

const CAMDEN_COLSWITCH_SECTIONS = [
  {
    title: "Primary Match — 36\" x 6\" Aluminum Push Plate",
    intro: "Camden's standard aluminum push plate is used as the baseline. BEA and Wikk are each compared against Camden independently — BEA and Wikk are not compared directly to each other.",
    columns: ["Spec", "Camden CM-7536/4", "BEA 10LPR36-HW", "Wikk S-i36-3-CLEAR"],
    rows: [
      ["Length", "36\"", "36\"", "36\""],
      ["Width", "6\"", "~6\" (216 sq in activation area)", "6\""],
      ["Depth", "3\" (76.2mm)", "1\"", "1.62\" (41mm)"],
      ["Face material", "Aluminum, anodized clear finish", "304 stainless steel", "Aluminum 6063-T5, Clear Anodized (628)"],
      ["Logo", "Wheelchair + \"Push to Open\"", "Wheelchair + \"Push to Open\"", "ISA + \"Push to Open\" (Logo code \"3\")"],
      ["Switch type", "Momentary", "Membrane switch", "Momentary"],
      ["Contact type", "SPDT, Form 'C'", "SPST N.O.", "SPDT micro-switch, NO or NC configurable"],
      ["Contact rating", "15A @ 30VDC", "1W, <100mA", "15A @ 125/250VAC; 3/4hp @ 125VAC"],
      ["Power", "None — dry contact", "Hardwired", "N/A (dry contact)"],
      ["Compatible connectivity", "N/A", "—", "Low-energy automatic door operators"],
      ["Max temp rating", "Not specified", "Not specified", "-40°F to 221°F (-40°C to 105°C)"],
      ["Listed", "—", "—", "UL and CSA"],
      ["Mounting", "Surface mount, no back box", "Wall or bollard", "—"],
      ["Stock availability", "Standard catalog item", "—", "Ships in 2-3 business days"],
    ],
    note: "Note — Stainless & Contact Rating: Camden's stainless CM-7536SS is the closer material match to BEA's stainless face. Separately, Wikk's switch is rated for line-voltage AC loads (125/250VAC, 3/4hp) — capable of switching a motor or operator directly — while Camden and BEA's contacts are lower-rated signal contacts meant to feed a controller input.",
  },
  {
    title: "Narrower Width Option — Camden CM-7436 (4-1/2\" Aluminum)",
    columns: ["Spec", "Camden CM-7436", "BEA", "Wikk I36NAR"],
    rows: [
      ["Width", "4-1/2\" (114mm)", "No narrow-width option — BEA makes the LPR36 in one width only", "4\" (102mm)"],
      ["Depth", "3\"", "—", "1.62\" (41mm)"],
    ],
    note: "BEA has no narrower-width equivalent. Wikk's narrow width (4\") is close to Camden's (4-1/2\"), though clear anodized in narrow width (S-I36NAR-3-CLEAR) is not listed as a stock SKU on Wikk's sheet — only PCCLEAR, PCDB, and US32D show as stock in narrow width, so clear anodized narrow would need to be custom-ordered.",
  },
  {
    title: "Stainless Option — Camden CM-7536SS",
    columns: ["Finish", "Camden", "BEA", "Wikk"],
    rows: [
      ["Stainless (satin/brushed)", "CM-7536SS — brushed stainless steel", "304 stainless is BEA's standard (only) face material", "US32D — Satin Stainless Steel 304 (630)"],
      ["Stainless (polished/mirror)", "—", "—", "US32 — Mirror Stainless Steel 304 (629), no Camden equivalent"],
    ],
    note: "Stock example: S-I36-3-US32D ships in 2-3 business days.",
  },
  {
    title: "Wireless Match — Camden CM-7536K",
    columns: ["Spec", "Camden CM-7536K", "BEA 10LPR36-300/-433/-900", "Wikk"],
    rows: [
      ["Face", "Aluminum, anodized clear finish", "Stainless steel", "Aluminum (per stock finish)"],
      ["Transmitter", "Built-in Kinetic™ (no battery, energy-harvesting)", "Choice of 300, 433, or 900 MHz RF (battery powered)", "\"Ready for wireless\" per feature list — no specific transmitter SKU published on this sheet"],
      ["Required receiver", "CM-RX-90", "10R300 / 10RD433 / 10RD900 (frequency-matched)", "Not specified — confirm with Wikk"],
    ],
  },
];

const CAMDEN_COLSWITCH_NOTES = [
  "Camden's aluminum plate (3\" depth) is thicker than both BEA's slim 1\" profile and Wikk's 1.62\" profile — may matter in tight mounting conditions.",
  "Contact ratings vary widely: Wikk's is line-voltage AC (125/250VAC, 3/4hp) and could switch a motor directly; Camden's (15A @ 30VDC) and BEA's (1W, <100mA) are lower-voltage signal contacts meant to feed a controller — confirm what the door operator's input actually expects.",
  "No aluminum-to-aluminum equivalent exists on the BEA side — BEA's face is stainless only, which is a Camden/Wikk-only advantage in this comparison.",
  "Environmental rating: BEA documents -32°F to 212°F and Wikk documents -40°F to 221°F with explicit outdoor functionality; Camden's cut sheet does not list an environmental rating — confirm directly with Camden if the application is exterior or exposed.",
  "Wireless: Wikk states the switch is \"ready for hardwired or wireless products\" but this sheet lists no specific transmitter/receiver SKUs, unlike Camden's Kinetic™ (CM-7536K + CM-RX-90) and BEA's frequency-specific options — confirm with Wikk what their wireless option consists of before quoting against either.",
  "Finish breadth: Wikk goes well beyond both Camden and BEA — brass (US4 satin, US10B oil-rubbed antique), dark bronze anodized, full custom powder coat match, a stainless/powder-coated cap add-on (SSCAP/PCCAP), and LED indicator options (LEDB/LEDW).",
  "2-pole option: Wikk's \"2P\" option adds a second switch to control two separate circuits from one column — no equivalent from Camden or BEA on these sheets.",
];
